apiVersion: v1
kind: Service
metadata:
  name: spring-service
spec:
  selector:
    app: spring
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      nodePort: 30010
      targetPort: 8080